#!/bin/bash
for build in $(go tool dist list); do
    os="$(echo $build | cut -d'/' -f1)"
    arch="$(echo $build | cut -d'/' -f2)"
    target="dist/${os}/${arch}"

    if [ "$os" == "windows" ]; then 
        suffix=".exe" 
    fi
    export GOOS=$os 
    export GOARCH=$arch 
    export CGO_ENABLED=0 
    go build -ldflags="-s -w" -o ${target}/sdt${suffix} cmd/sdt/main.go 
    go build -ldflags="-s -w" -o ${target}/jsonformat${suffix} cmd/jsonformat/main.go
    go build -ldflags="-s -w" -o ${target}/gotree${suffix} cmd/gotree/main.go
    go build -ldflags="-s -w" -o ${target}/treesit${suffix} cmd/treesit/main.go
    if [ "$build" != "darwin/arm64" ]; then
        upx -qqq --best --lzma ${target}/sdt${suffix} &
        upx -qqq --best --lzma ${target}/jsonformat${suffix} &
        upx -qqq --best --lzma ${target}/gotree${suffix} &
        upx -qqq --best --lzma ${target}/treesit${suffix} &
    fi
done

